### ISSUE TITLE
Use directory name as family name

### ISSUE THREAD

**Issue by barbeque** [joymachinegames/megascan-assembler#3]
In the case where there is a directory named `Rock_Cliff_omfp70`, it should not use the family from the filenames inside it (`omfp7_4K`) but instead the more descriptive directory name.

**Comment by mittens** [comment]
![megascans_family_names](https://cloud.githubusercontent.com/assets/47236/23874499/39dec89a-080c-11e7-878b-881c1db00672.PNG)

Just to doubly-ensure we're on the same page, this is the issue.

**Comment by barbeque** [comment]
Done
